### ISSUE TITLE
Rendering of duplicated elements fails

### ISSUE THREAD

**Issue by nek0** [Twinside/rasterific-svg#3]
When rendering an svg image, which contains duplicated elements, only the original elements are rendered, not the duplicates.
for reference, see [here](https://eidolon.nek0.eu/medium/51).

**Comment by Twinside** [comment]
I got a fix for the positioning (so ashamed of this one...), but there is still a rendering bug near the hand of the skeleton, I need to investigate further

**Comment by Twinside** [comment]
Current rendering:

![51](https://cloud.githubusercontent.com/assets/168874/20459047/407c388c-aeb5-11e6-9056-83558a955cda.png)

**Comment by nek0** [comment]
Thanks for looking into it. Looks great so far.

**Comment by Twinside** [comment]
![51](https://cloud.githubusercontent.com/assets/168874/20462535/add0ca2c-af20-11e6-8a3b-fd048f793b2c.png)

Still some problem at the hand join, but as it's looking mostly OK, I'll may release this version today

**Comment by nek0** [comment]
Looks perfect to me. Thanks for the work.

**Comment by Twinside** [comment]
Released version [0.3.2.1](http://hackage.haskell.org/package/rasterific-svg-0.3.2.1)
